social:
 - {icon: 'twitter', link: 'https://twitter.com/jpweytjens'}
 - {icon: 'github', link: 'https://github.com/jpweytjens'}

academic:
 - {icon: 'orcid', link: 'https://orcid.org/0000-0002-2748-1524'}
 - {icon: 'osf', link: 'https://osf.io/v6wks/'}
